### Adding columns to a DataFrame

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

df = pd.DataFrame(data)

In [3]:
print('Data Frame Before New column:')
df.head()

Data Frame Before New column:

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [4]:
address = ['NYC', 'NJ', 'CA', 'PA']

df['Address'] = address

In [5]:
print('Data Fram After New Column:')
df.head()

Data Fram After New Column:

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

### Creating a new column using an old column(s)

In [6]:
print('Before Column Add:')
df.head()

Before Column Add:

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [7]:
# Add column using old columns
df['Total Score'] = df['Score 1'] + df['Score 2']

print('After Column Add:')
df.head()

After Column Add:

     Name  Height Qualification  Score 1  Score 2 Address  Total Score
0    Jane     5.1           Msc       56       50     NYC          106
1  Princi     6.2            MA       86       96      NJ          182
2   James     5.1           Msc       77       60      CA          137
3    Fadi     5.2           Msc       45       30      PA           75

In [8]:
df['Avg_Score'] = df['Total Score'] /2
df.head()

,Name,Height,Qualification,Score 1,Score 2,Address,Total Score,Avg_Score
0,Jane,5.1,Msc,56,50,NYC,106,53.0
1,Princi,6.2,MA,86,96,NJ,182,91.0
2,James,5.1,Msc,77,60,CA,137,68.5
3,Fadi,5.2,Msc,45,30,PA,75,37.5

### Importing Specified Columns and Rearranging them

In [9]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

# rearranging columns using columns attribute. We also can exclude columns (weight)
df2 = pd.DataFrame(data, columns=['Score 1', 'Score 2', 'Name', 'Qualification'])
print(df2)

   Score 1  Score 2    Name Qualification
0       56       50    Jane           Msc
1       86       96  Princi            MA
2       77       60   James           Msc
3       45       30    Fadi           Msc

In [10]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]

df3 = pd.DataFrame(values, columns=['Name', 'Univ_Marks'])

df3.head()

     Name  Univ_Marks
0   Rohan         455
1  Elvish         250
2    John         495
3     Sai         400
4    Eric         350

In [11]:
df3['Percentage'] = (df3['Univ_Marks'] / 500) * 100

df3.head()

     Name  Univ_Marks  Percentage
0   Rohan         455        91.0
1  Elvish         250        50.0
2    John         495        99.0
3     Sai         400        80.0
4    Eric         350        70.0

### Using the .insert() method to add a column

In [12]:
df3.insert(3, 'Age', [1000, 2000, 50, 60, 12, 13])

df3.head()

     Name  Univ_Marks  Percentage   Age
0   Rohan         455        91.0  1000
1  Elvish         250        50.0  2000
2    John         495        99.0    50
3     Sai         400        80.0    60
4    Eric         350        70.0    12

### Using .assign() to create a new column

In [13]:
df3 = df3.assign(location=['MiddleEarth', 'Forgotten Lands', 'NYC', 'NJ', 'CA', 'MA'] )
df3.head()

     Name  Univ_Marks  Percentage   Age         location
0   Rohan         455        91.0  1000      MiddleEarth
1  Elvish         250        50.0  2000  Forgotten Lands
2    John         495        99.0    50              NYC
3     Sai         400        80.0    60               NJ
4    Eric         350        70.0    12               CA