### Converting Columns

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_json('data/cars.json')

In [8]:
df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

### Convert Pandas Column to list using .tolist()

In [10]:
col_list = df['Car'].values.tolist()
print('CarLists:', col_list)

CarLists: ['Chevrolet Vega', 'Chevrolet Vega (sw)', 'Chevrolet Vega 2300', 'Chevrolet Woody', 'Chevrolete Chevelle Malibu', 'Chevy C20', 'Chevy S-10', 'Chrysler Cordoba', 'Chrysler Lebaron Medallion', 'Chrysler Lebaron Salon', 'Chrysler Lebaron Town @ Country (sw)', 'Chrysler New Yorker Brougham', 'Chrysler Newport Royal', 'Citroen DS-21 Pallas', 'Datsun 1200', 'Datsun 200SX', 'Datsun 200-SX', 'Datsun 210', 'Datsun 210', 'Datsun 210 MPG', 'Datsun 280-ZX', 'Datsun 310', 'Datsun 310 GX', 'Datsun 510', 'Datsun 510 (sw)', 'Datsun 510 Hatchback', 'Datsun 610', 'Datsun 710', 'Datsun 710', 'Datsun 810', 'Datsun 810 Maxima', 'Datsun B210', 'Datsun B-210', 'Datsun B210 GX', 'Datsun F-10 Hatchback', 'Datsun PL510', 'Datsun PL510', 'Dodge Aries SE', 'Dodge Aries Wagon (sw)', 'Dodge Aspen', 'Dodge Aspen', 'Dodge Aspen 6', 'Dodge Aspen SE', 'Dodge Challenger SE', 'Dodge Charger 2.2', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt (sw)', 'Dodge Colt Hardtop', 'Dodge Colt Hatchback Custom', 'Dodge Colt m/m', 'Dodge Coronet Brougham', 'Dodge Coronet Custom', 'Dodge Coronet Custom (sw)', 'Dodge D100', 'Dodge D200', 'Dodge Dart Custom', 'Dodge Diplomat', 'Dodge Magnum XE', 'Dodge Monaco (sw)', 'Dodge Monaco Brougham', 'Dodge Omni', 'Dodge Rampage', 'Dodge St. Regis', 'Fiat 124 Sport Coupe', 'Fiat 124 TC', 'Fiat 124B', 'Fiat 128', 'Fiat 128', 'Fiat 131', 'Fiat Strada Custom', 'Fiat x1.9', 'Ford Country', 'Ford Country Squire (sw)', 'Ford Country Squire (sw)', 'Ford Escort 2H', 'Ford Escort 4W', 'Ford F108', 'Ford F250', 'Ford Fairmont', 'Ford Fairmont (auto)', 'Ford Fairmont (man)', 'Ford Fairmont 4', 'Ford Fairmont Futura', 'Ford Fiesta', 'Ford Futura', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino (sw)', 'Ford Gran Torino (sw)', 'Ford Grenada', 'Ford Grenada ghia', 'Ford Grenada gl', 'Ford Grenada l', 'Ford LTD', 'Ford LTD', 'Ford LTD Landau', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Mustang', 'Ford Mustang Boss 302', 'Ford Mustang Cobra', 'Ford Mustang GL', 'Ford Mustang II', 'Ford Mustang II 2+2', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto (sw)', 'Ford Pinto Runabout', 'Ford Ranger', 'Ford Thunderbird', 'Ford Torino', 'Ford Torino (sw)', 'Ford Torino 500', 'Hi 1200D', 'Honda Accord', 'Honda Accord', 'Honda Accord CVCC', 'Honda Accord LX', 'Honda Civic', 'Honda Civic', 'Honda Civic', 'Honda Civic (auto)', 'Honda Civic 1300', 'Honda Civic 1500 gl', 'Honda Civic CVCC', 'Honda Civic CVCC', 'Honda Prelude', 'Mazda 626', 'Mazda 626', 'Mazda GLC', 'Mazda GLC 4', 'Mazda GLC Custom', 'Mazda GLC Custom l', 'Mazda GLC Deluxe', 'Mazda GLC Deluxe', 'Mazda RX2 Coupe', 'Mazda RX3', 'Mazda RX-4', 'Mazda RX-7 GS', 'Mercedes Benz 300d', 'Mercedes-Benz 240d', 'Mercedes-Benz 280s', 'Mercury Capri 2000', 'Mercury Capri v6', 'Mercury Cougar Brougham', 'Mercury Grand Marquis', 'Mercury Lynx l', 'Mercury Marquis']

In [11]:
df.Car.values.tolist()

['Chevrolet Vega',
 'Chevrolet Vega (sw)',
 'Chevrolet Vega 2300',
 'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',
 'Chevy C20',
 'Chevy S-10',
 'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',
 'Chrysler Lebaron Salon',
 'Chrysler Lebaron Town @ Country (sw)',
 'Chrysler New Yorker Brougham',
 'Chrysler Newport Royal',
 'Citroen DS-21 Pallas',
 'Datsun 1200',
 'Datsun 200SX',
 'Datsun 200-SX',
 'Datsun 210',
 'Datsun 210',
 'Datsun 210 MPG',
 'Datsun 280-ZX',
 'Datsun 310',
 'Datsun 310 GX',
 'Datsun 510',
 'Datsun 510 (sw)',
 'Datsun 510 Hatchback',
 'Datsun 610',
 'Datsun 710',
 'Datsun 710',
 'Datsun 810',
 'Datsun 810 Maxima',
 'Datsun B210',
 'Datsun B-210',
 'Datsun B210 GX',
 'Datsun F-10 Hatchback',
 'Datsun PL510',
 'Datsun PL510',
 'Dodge Aries SE',
 'Dodge Aries Wagon (sw)',
 'Dodge Aspen',
 'Dodge Aspen',
 'Dodge Aspen 6',
 'Dodge Aspen SE',
 'Dodge Challenger SE',
 'Dodge Charger 2.2',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt (sw)',
 'Dodge Colt Hardtop',
 'Dodge Colt Hatchback Custom',
 'Dodge Colt m/m',
 'Dodge Coronet Brougham',
 'Dodge Coronet Custom',
 'Dodge Coronet Custom (sw)',
 'Dodge D100',
 'Dodge D200',
 'Dodge Dart Custom',
 'Dodge Diplomat',
 'Dodge Magnum XE',
 'Dodge Monaco (sw)',
 'Dodge Monaco Brougham',
 'Dodge Omni',
 'Dodge Rampage',
 'Dodge St. Regis',
 'Fiat 124 Sport Coupe',
 'Fiat 124 TC',
 'Fiat 124B',
 'Fiat 128',
 'Fiat 128',
 'Fiat 131',
 'Fiat Strada Custom',
 'Fiat x1.9',
 'Ford Country',
 'Ford Country Squire (sw)',
 'Ford Country Squire (sw)',
 'Ford Escort 2H',
 'Ford Escort 4W',
 'Ford F108',
 'Ford F250',
 'Ford Fairmont',
 'Ford Fairmont (auto)',
 'Ford Fairmont (man)',
 'Ford Fairmont 4',
 'Ford Fairmont Futura',
 'Ford Fiesta',
 'Ford Futura',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino (sw)',
 'Ford Gran Torino (sw)',
 'Ford Grenada',
 'Ford Grenada ghia',
 'Ford Grenada gl',
 'Ford Grenada l',
 'Ford LTD',
 'Ford LTD',
 'Ford LTD Landau',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Mustang',
 'Ford Mustang Boss 302',
 'Ford Mustang Cobra',
 'Ford Mustang GL',
 'Ford Mustang II',
 'Ford Mustang II 2+2',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto (sw)',
 'Ford Pinto Runabout',
 'Ford Ranger',
 'Ford Thunderbird',
 'Ford Torino',
 'Ford Torino (sw)',
 'Ford Torino 500',
 'Hi 1200D',
 'Honda Accord',
 'Honda Accord',
 'Honda Accord CVCC',
 'Honda Accord LX',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic (auto)',
 'Honda Civic 1300',
 'Honda Civic 1500 gl',
 'Honda Civic CVCC',
 'Honda Civic CVCC',
 'Honda Prelude',
 'Mazda 626',
 'Mazda 626',
 'Mazda GLC',
 'Mazda GLC 4',
 'Mazda GLC Custom',
 'Mazda GLC Custom l',
 'Mazda GLC Deluxe',
 'Mazda GLC Deluxe',
 'Mazda RX2 Coupe',
 'Mazda RX3',
 'Mazda RX-4',
 'Mazda RX-7 GS',
 'Mercedes Benz 300d',
 'Mercedes-Benz 240d',
 'Mercedes-Benz 280s',
 'Mercury Capri 2000',
 'Mercury Capri v6',
 'Mercury Cougar Brougham',
 'Mercury Grand Marquis',
 'Mercury Lynx l',
 'Mercury Marquis']

### Convert Pandas column to a Numpy Array

In [14]:
col_numpy_arr = df['Car'].to_numpy()
print(type(col_numpy_arr))

<class 'numpy.ndarray'>

In [15]:
df[df.columns[0]].values.tolist()

['Chevrolet Vega',
 'Chevrolet Vega (sw)',
 'Chevrolet Vega 2300',
 'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',
 'Chevy C20',
 'Chevy S-10',
 'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',
 'Chrysler Lebaron Salon',
 'Chrysler Lebaron Town @ Country (sw)',
 'Chrysler New Yorker Brougham',
 'Chrysler Newport Royal',
 'Citroen DS-21 Pallas',
 'Datsun 1200',
 'Datsun 200SX',
 'Datsun 200-SX',
 'Datsun 210',
 'Datsun 210',
 'Datsun 210 MPG',
 'Datsun 280-ZX',
 'Datsun 310',
 'Datsun 310 GX',
 'Datsun 510',
 'Datsun 510 (sw)',
 'Datsun 510 Hatchback',
 'Datsun 610',
 'Datsun 710',
 'Datsun 710',
 'Datsun 810',
 'Datsun 810 Maxima',
 'Datsun B210',
 'Datsun B-210',
 'Datsun B210 GX',
 'Datsun F-10 Hatchback',
 'Datsun PL510',
 'Datsun PL510',
 'Dodge Aries SE',
 'Dodge Aries Wagon (sw)',
 'Dodge Aspen',
 'Dodge Aspen',
 'Dodge Aspen 6',
 'Dodge Aspen SE',
 'Dodge Challenger SE',
 'Dodge Charger 2.2',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt',
 'Dodge Colt (sw)',
 'Dodge Colt Hardtop',
 'Dodge Colt Hatchback Custom',
 'Dodge Colt m/m',
 'Dodge Coronet Brougham',
 'Dodge Coronet Custom',
 'Dodge Coronet Custom (sw)',
 'Dodge D100',
 'Dodge D200',
 'Dodge Dart Custom',
 'Dodge Diplomat',
 'Dodge Magnum XE',
 'Dodge Monaco (sw)',
 'Dodge Monaco Brougham',
 'Dodge Omni',
 'Dodge Rampage',
 'Dodge St. Regis',
 'Fiat 124 Sport Coupe',
 'Fiat 124 TC',
 'Fiat 124B',
 'Fiat 128',
 'Fiat 128',
 'Fiat 131',
 'Fiat Strada Custom',
 'Fiat x1.9',
 'Ford Country',
 'Ford Country Squire (sw)',
 'Ford Country Squire (sw)',
 'Ford Escort 2H',
 'Ford Escort 4W',
 'Ford F108',
 'Ford F250',
 'Ford Fairmont',
 'Ford Fairmont (auto)',
 'Ford Fairmont (man)',
 'Ford Fairmont 4',
 'Ford Fairmont Futura',
 'Ford Fiesta',
 'Ford Futura',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Galaxie 500',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino',
 'Ford Gran Torino (sw)',
 'Ford Gran Torino (sw)',
 'Ford Grenada',
 'Ford Grenada ghia',
 'Ford Grenada gl',
 'Ford Grenada l',
 'Ford LTD',
 'Ford LTD',
 'Ford LTD Landau',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Maverick',
 'Ford Mustang',
 'Ford Mustang Boss 302',
 'Ford Mustang Cobra',
 'Ford Mustang GL',
 'Ford Mustang II',
 'Ford Mustang II 2+2',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto',
 'Ford Pinto (sw)',
 'Ford Pinto Runabout',
 'Ford Ranger',
 'Ford Thunderbird',
 'Ford Torino',
 'Ford Torino (sw)',
 'Ford Torino 500',
 'Hi 1200D',
 'Honda Accord',
 'Honda Accord',
 'Honda Accord CVCC',
 'Honda Accord LX',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic',
 'Honda Civic (auto)',
 'Honda Civic 1300',
 'Honda Civic 1500 gl',
 'Honda Civic CVCC',
 'Honda Civic CVCC',
 'Honda Prelude',
 'Mazda 626',
 'Mazda 626',
 'Mazda GLC',
 'Mazda GLC 4',
 'Mazda GLC Custom',
 'Mazda GLC Custom l',
 'Mazda GLC Deluxe',
 'Mazda GLC Deluxe',
 'Mazda RX2 Coupe',
 'Mazda RX3',
 'Mazda RX-4',
 'Mazda RX-7 GS',
 'Mercedes Benz 300d',
 'Mercedes-Benz 240d',
 'Mercedes-Benz 280s',
 'Mercury Capri 2000',
 'Mercury Capri v6',
 'Mercury Cougar Brougham',
 'Mercury Grand Marquis',
 'Mercury Lynx l',
 'Mercury Marquis']

In [ ]:
# List of df indexes
df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160]

### Rename a column in Pandas

- .rename()

In [18]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

tech_df = pd.DataFrame(tech)

In [20]:
tech_df = df.rename(columns = {'Courses': 'Course Name'})

In [21]:
tech_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork